---
- name: ovn-kubernetes | Create kubernetes dir
  win_file:
    path: "{{ download_info.install_path }}"
    state: directory

- name: ovn-kubernetes | Create CNI dir
  win_file:
    path: "{{ download_info.install_path }}/cni"
    state: directory

- name: ovn-kubernetes | get kubernetes binaries
  win_copy:
    src: "{{ansible_tmp_dir}}/{{item}}"
    dest: "{{ download_info.install_path }}/{{item}}"
  with_items:
    - ovnkube.exe
    - kubectl.exe
    - kubelet.exe
    - bootstrap-kubeconfig
    - kubelet-ca.crt
    - kubelet-config

- name: ovn-kubernetes | get cni binary
  win_copy:
    src: "{{ansible_tmp_dir}}/ovn-k8s-cni-overlay.exe"
    dest: "{{ download_info.install_path }}\\cni\\ovn-k8s-cni-overlay.exe"
