---
- hosts: localhost
  any_errors_fatal: true
  tasks:
    # This directory is used only for caching files on the Ansible host
    # in order to speed up the deployment time on subsequent playbook runs.
    - name: ovn-kubernetes | Create local Ansible temporary directory
      file:
        path: "{{ ansible_tmp_dir }}"
        state: directory

    - name: ovn-kubernetes | Pull ignition file from cluster
      shell: oc get machineconfig| awk '/rendered-worker.*/{print $1;exit}'| xargs oc get machineconfig -o json | jq '.spec.config' > worker.ign
      args:
        chdir: "{{ ansible_tmp_dir }}"

    - name: ovn-kubernetes | Generate bootstrap files
      command: ./wmcb ./worker.ign ./
      args:
        chdir: "{{ ansible_tmp_dir }}"

- hosts: windows_workers
  remote_user: Administrator
  gather_facts: true
  become_method: runas
  any_errors_fatal: true
  tasks:
    - set_fact:
        windows_container_tag: 1709
      when: ansible_kernel == windows1709
    - set_fact:
        windows_container_tag: 1803
      when: ansible_kernel == windows1803
    - set_fact:
        windows_container_tag: 1809
      when: ansible_kernel == windows2019
    - import_role:
        name: windows/version_check
    - import_role:
        name: windows/requirements
    - import_role:
        name: windows/docker
    - import_role:
        name: windows/openvswitch
      vars:
        # This is useful when using custom OVS MSI, it should also provide the link
        # to the certificates which need to be added in certstore in order to be able
        # to install the MSI in unattended mode
        # Setting install_beta_ovs to false will install the latest stable OVS
        install_custom_ovs: true
        custom_ovs_link: "https://cloudbase.it/downloads/openvswitch-hyperv-installer-beta-2.10.msi"
        # This is useful for dev purposes and when using custom MSI which is not signed
        bcdedit_needed: false
        # ovs_certs_link: ""  # link to certificates for OVS if required
    - import_role:
        name: windows/ovn-kubernetes
    - import_role:
        name: windows/kubernetes

- hosts: windows_workers
  remote_user: Administrator
  gather_facts: true
  become_method: runas
  any_errors_fatal: true
  tasks:
    - import_role:
        name: windows/validation
