---
sdn_info:
  sdn_network_name: external

ovs_cmd_timeout: 30

kubernetes_info:
  MASTER_IP: ""
  CLUSTER_SUBNET: "10.128.0.0/14/23"
  K8S_DNS_DOMAIN: "{{K8S_DNS_DOMAIN | default('cluster.local')}}"
  K8S_DNS_SERVICE_IP: "{{K8S_DNS_SERVICE_IP | default('10.0.9.10')}}"
  K8S_API_SERVICE_IP: "{{K8S_API_SERVICE_IP | default('10.0.9.1')}}"
  NB_ADDR: "tcp://10.0.136.123:6641"
  SB_ADDR: "tcp://10.0.136.123:6642"
  SERVICE_CIDR: "172.30.0.0/16"
  TOKEN: ""
  infracontainername: "ovnkubernetes/pause"

firewall:
  disable_completely: true  # WARNING: Do NOT enable this in production. Used only for testing purposes.

  rules:
    - name: "Open vSwitch OVN GENEVE Port"
      protocol: "UDP"
      port: 6081
      direction: "Inbound"

    - name: "Open vSwitch OVN Database Ports"
      protocol: "TCP"
      port: 6641-6642
      direction: "Inbound"

    - name: "Kubernetes TCP Service Ports"
      protocol: "TCP"
      port: 30000-32767
      direction: "Inbound"

    - name: "Kubernetes UDP Service Ports"
      protocol: "UDP"
      port: 30000-32767
      direction: "Inbound"

    - name: "Kubernetes Kubelet Ports"
      protocol: "TCP"
      port: 10250-10252
      direction: "Inbound"

    - name: "Kubernetes HTTP API Port"
      protocol: "TCP"
      port: 8080
      direction: "Inbound"

    - name: "Kubernetes HTTPS API Port"
      protocol: "TCP"
      port: 443
      direction: "Inbound"
